---
title: "行動規範"
---

# Code of Conduct

当研究室では多様性を重視し、国際的な学術研究・技術コミュニティへの貢献を目標としています。 
その目標に向けて、我々メンバーは下記の項目にコミットします。  

- 性別、宗教、国籍その他個人的属性に基づく差異を尊重し、それらの多様性を強みとするための環境醸成に努めます。  
  
- 研究室という狭いコミュニティに閉じこもることなく、積極的に国内外の他研究グループのとの交流を図ります。 
  
- 研究室に所属するメンバーはたとえ学生であっても研究者です。 
研究者としての自覚をもち、不正（剥奪や結果や改竄、捏造、盗用など）を実施しないように相互レビューを重視します。 
  
- 研究者として、またチームとして学会発表、論文発表を目指します。 
メンバーが時間をかけて取り組む研究の成果を発表することで学術的に価値あるものとし、国内外の学術研究コミュニティーへの貢献に努めます。 
  
- 研究室というコミュニティとして個々人の問題や課題をサポートします。 
研究室のメンバーはいかなる場合であっても仲間であり見捨てる存在ではありません。 
それぞれの短所を補うことはチームとしてのアドバンテージです。 
  
- コミュニティへ貢献します。 
研究室内だけでなく、国内外のコミュニティへのコミットを期待します。  

<br>

Our goal is to contribute to international academic research and technical communities. 
To achieve this goal, we, the members, are committed to the following items.  

- Respecting differences based on gender, religion, nationality, and other personal attributes, and striving to foster an environment where such diversity can be used as a strength.  

- We will not confine ourselves to the narrow community of our laboratory, but will actively seek to interact with other research groups in Japan and abroad.  

- All members of the laboratory are researchers, even if they are students. 
We will be aware of our roles as researchers, and place importance on mutual review to prevent misconduct (deprivation, falsification of results, fabrication, plagiarism, etc.).  

- We will strive to contribute to the academic research community both in Japan and abroad by presenting the achievements of our researches at conferences and publish papers that our members spend their time working on to make it academically valuable.

- We will support each individual's problems and issues as a team and we do not abandon them. It is an advantage to work as a team to compensate for each individual's shortcomings.  

- We will commit to the community, not only to the lab, but also to related research groups and engineering communities.  

