---
title: "Geographic Information Science Lab at Saitama University"
output:
  html_document:
    includes:
      in_header: cover_with_logo.html
---

## 埼玉大学大学院理工学研究科　数理電子情報部門情報領域 
## 地理情報科学研究室

<br>

### Updates
- 10 May 2022. Proposed two presentations have been accepted in COSIT2022.
- 6 May 2022. [new publication] Percival, Tsutsumida, Murakami, Yoshida, and Nakaya (2022) gwpcorMapper: an interactive mapping tool for exploring geographically weighted correlation and partial correlation in high-dimensional geospatial datasets has been accepted in Journal of Geovisualization and Spatial Analysis. The [preprint](https://arxiv.org/abs/2101.03491) is now available in Arxiv.
- 22 Apr. 2022. [new publication] Tsutsumida, Shin, and Miura (2022) [Evaluation of Land Surface Phenology for Autumn Leaf Color Change Based on Citizen Reports across Japan](https://www.mdpi.com/2072-4292/14/9/2017/htm) has been published in Remote Sensing.
- 5 Apr. 2022. Two presentations have been accepted in IGARSS2022.
- 1 Apr. 2022. Two postgraduate students are joined.
- 17Mar. 2022. Discussions on Ecological studies by open science and citizen science approaches was held on ESJ69. 
- 15 Mar. 2022. A poster was presented on ESJ69 (Funada and Tsutsumida, 2022). 
- 11 Mar. 2022. 'Integration of multiscale and multiangle remote sensing data' was presented on act-x annual meeting. 
- 8 Mar. 2022.  5 undergrad students have been joined.
- 24 Jan. 2022. A lecture was delivered at Kasukabe Girls' senior high school. 
- 22 Jan. 2022. [new publication] A preprint [Mapping cherry blossoms from geotagged street-level photos](https://doi.org/10.1101/2022.01.18.476550) is appeared at bioRxiv. 
- 18 Jan. 2022. [new publication] Doi, Osawa, and Tsutsumida (2022) [Assessing the potential repercussions of the COVID‑19 pandemic on global SDG attainment](https://link.springer.com/article/10.1007/s43621-021-00067-2) in Discover Sustainability. We demonstrated comprehensive analyses of the impact of lockdown toward SDG's achievement.  
- 17 Jan. 2022. [new publication] Tsutsumida (2022) Teaching reproducible Geocomputation Online, Theory and Application of GIS.  

<br> 

<details>
  <summary>Archives</summary>
  - 17 Dec. 2021. AGU Fall meeting 2021で発表を行いました（Tsutsumida et al.）。
  - 31 Oct. 2021. 第30回地理情報システム学会研究発表大会で４件の関連研究を発表しました（堤田ら、村上ら、吉田ら、Thongrueang et al.）。
  - 1 Oct. 2021. 10月29日に日本写真測量学会関西支部にて「土地被覆分類データの空間精度・空間誤差」を[講演](http://www.jsprs-w.org)します。
  - 29 Sep. 2021. [Murakami et al.](https://escholarship.org/uc/item/8kg664zg), [Yoshida et al.](https://escholarship.org/uc/item/62s7n79k)をGIScience2021にて発表しました。
  - 28 Sep. 2021. Kato and Tsutsumidaをsilvilaserにて発表しました。
  - 21 Sep. 2021. Act-xに採択されました。
  - 18 Sep. 2021. 科学者の芽(HiGEPS)にて高校生向けの講義を担当しました。
  - 15 Sep. 2021. [Nagai et al.](https://www.frontiersin.org/articles/10.3389/ffgc.2021.659910/abstract)がFrontiers in Forests and Global Changeにアクセプトされました。
  - 27 Jul. 2021. 千葉大環境リモートセンシング研究センターの共同利用研究「長期全球観測衛星画像データをもちいた土地被覆変動の解明」が採択されました。  
  - 1 Jul. 2021. 情報・システム研究機構 データサイエンス共同利用基盤施設（ROIS-DS）共同研究「空間集計単位と空間スケールに着目した地理空間モデリング」が採択されました。  
  - 26 May. 2021. GIS-理論と応用 より展望論文「地理的加重法の研究動向と今後の展望」が発表されました。
  - 7 Apr. 2021. R CRANにて [gwpcormapper](https://cran.r-project.org/web/packages/gwpcormapper/index.html) を公開しました。  
  - 1 Apr. 2021. 事務補佐員１名が加わり、研究室メンバーは計６名となりました。  
  - 31 Mar. 2021. 「地理的加重法の研究動向と今後の展望」が「GIS-理論と応用」に採択されました。  
  - 9 Mar. 2021.  ３年生４名が配属されました。/ 4 undergraduate students are joined.  
  - 18 Feb. 2021. 千葉大学CEReS環境リモートセンシングシンポジウムでポスター発表を行います。  
  - 5 Feb. 2021. 情報・システム研究機構 データサイエンス共同利用基盤施設（ROIS-DS）にて「地理的加重モデルの開発と空間データ解析」の[講演](https://ds.rois.ac.jp/article/rois-ds_symposium_20210205/)を行います。  
  - 6 Jan 2021. 当研究室を開設しました。/ The GISci lab at Saitama University is newly opend.  
</details> 
