---
title: "参加希望者へ"
output: html_document
---

# Messages to those who are interested in joining our team
  
<br>

# 学生の方へ
# To students
## 配属希望の３年生へ
## To third grade undergraduate students in the department of Information and Computer Sciene, Saitama University
2021年1月に開設した研究室ですので、新たな環境で１からチームを作っていきたい方、自発的に研究に取り組める方をお待ちしています。 

Our laboratory was established in January 2021. 
We are looking forward to those who want to build a team from scratch in a new environment. 

<br>


## 博士前期・後期課程にて進学希望の方へ
## To potential post-graduate students
当研究室では多様性を重視し、様々な専門知識を有する方を歓迎します。 
そのため情報工学を学んだ学生以外でも興味があれば受け入れ可能です。
また、博士号取得を目指す社会人の進学希望者も歓迎します。 
受験に関する詳しい情報は[こちら](http://www.ics.saitama-u.ac.jp/exam/in/)を御覧ください。 
進学希望者は試験を受験する前に受け入れ教員との事前の面談および研究計画書の提出が必要です。 
Inquiryページより問い合わせください。  

We value diversity and welcome students with various kinds of expertise. 
Therefore, even students who have not studied information and computer science can be accepted if they are interested. 
We also welcome engineers and analysts working on a company, who wish to pursue a doctoral degree. 
For more information about the examination, please visit [here](http://www.ics.saitama-u.ac.jp/exam/in/). 
Applicants are required to submit your research proposal and to have a preliminary interview with the PI before taking the examination. 
Please contact us via the Inquiry page.  


<br>

## 研究生希望の方へ
## To potential research students
博士前期・後期課程に進学希望者に対して研究生としての受け入れが可能です。 
[こちら](http://www.saitama-u.ac.jp/rikogaku/admission/exam/research_student.html)を御覧ください。  
研究生希望者は申請前に受け入れ教員との事前の面談および研究計画書の提出が必要です。 
Inquiryページより問い合わせください。  

For those who wish to enter the Master's or Doctoral course, we can accept them as research students. 
Please refer to [here](http://www.saitama-u.ac.jp/rikogaku/admission/exam/research_student.html).  
Those who wish to become research students need to submit your research proposal and to have a preliminary interview with the PI before the applocation. 
Please contact us via the Inquiry page.

<br>


## 研究の進め方について
## Plans for supervision
地理情報を扱い研究を進めるにあたりプログラミングスキルは必須です。 
なかでもR、Python、Javascript（頻度順）を多用します。 
ちなみにこのHPもRで書いています。 
配属された学部生は、これらのツールでの地理情報データ処理を配属後にみんなで学習していきます。 
博士前期・後期課程進学希望者は入学前にある程度のスキルを有していることを必須とします。  
  
研究テーマはそれぞれの興味を尊重し、ディスカッションを通じて固めていきます。 
想定されるおおまかなトピックは研究室概要やpublicationsのページを眺めてみてください。 
研究の世界では、若い学生の柔軟な発想が驚くべき研究テーマに結びつくこともあります。 
また研究上は、教員と学生という縦の関係ではなく、研究者同士のフラットな関係を目指しましょう。  
当研究室にて大学院への進学を希望する学生へは３年間、もしくは６年間の時間をかけて取り組むべきテーマ設定をともに考えます。 
博士前期課程以上の学生は国際会議での発表や査読付き英語論文の発表を目指します。 
その他の学生は地理情報科学の一連の研究プロセスを体験してもらい社会に役立つスキルを包括的に学んでもらいます。 
進捗次第では国内学会での発表や査読付き論文の発表を目指します。 
いずれにせよ、地理情報をもちいて環境や社会の課題解決に向けた研究に取り組みます。  

Programming skills are essential to deal with geographic information for research. 
We use R, Python, and Javascript a lot (This website is also written in R). 
The undergraduates assigned to our lab will learn how to process geographic information data using these tools together. 
Students who wish to enter the Master's and Doctoral programs are required to have some skills prior to the program.    
  
The research theme will be determined through discussions, with fully consideration of each student's interest. 
Please find potential topics at the overview page. 
The flexible ideas from students are sometimes worth to lead to surprising research topics. 
As we regard students as researchers, we expect to build a flat relationship between researchers, rather than a vertical relationship between the PI and students for research activities. 
For students who wish to go on to graduate school in our laboratory, we will carefully set up their themes to work on over a period of three or six years. 
Students in the Master's program and above are expected to present their work at international conferences and publish refereed papers in English. 
Other students will experience a series of workflow in geographic information science and learn comprehensive skills useful for your future careers. 
Depending on their progress, they will aim to present their work at domestic conferences or publish refereed papers. 
In any case, students will engage in research that uses geographic information to solve environmental and social problems. 

<br>

## こんな人に来てほしいリスト
## A list of soft skills for potential members
- <u> _アイデアが豊富な人_ </u>   
  <u> _those who have plenty of ideas_ </u>   
そもそも研究は100のアイデアのうち3つ成功すればよい、というレベルの仕事です。 
想像力があり色々な発想ができる人が望ましいです。  
Research is a level of work where you only need to succeed in 3 out of 100 ideas. 
It is desirable for potential members to be imaginative and able to come up with a variety of ideas.   

- <u> _向上心のある人_ </u>    
  <u> _those who with ambition_ </u>    
地理情報に関連する技術は日々進歩しています。コンフォートゾーンにとどまらず常に最新技術の習得に注力し、最新の研究動向をフォローアップできることが望ましいです。  
Geographic information technologies are advancing quickly. It is desirable to always focus on learning the latest technology and follow up on the latest research trends, not just staying in your comfort zone.

- <u> _英語に抵抗感がない人_ </u>   
  <u> _those who are not afraid of English_ </u>   
地理情報科学分野の最新研究の多くは英語論文や国際学会で発表されます。現時点で論文が読めたり英語でのプレゼンテーションができるほどの英語力がなくても、それらが当たり前にできるよう努力する人が望ましいです。  
Most of the latest research in the field of geographic information science is presented in  international conferences and journals. Even if you do not have the English skills to read papers or make presentations in English at this time, it is desirable that you make efforts to master English skills through research activities.  


- <u> _地図が好きな人_ </u>   
  <u> _those who love maps_ </u>   
地理情報科学に関する研究成果は地図として発表することが多いです。 衛星画像や地理情報を用いた作図に楽しみを感じる人が望ましいです。  
Achievements on geographic information science are often presented as maps. 
Members who enjoy drawing maps from satellite images and geographic information are preferred. 


- <u> _フィールドでの体験から課題を見出すことができる人_ </u>   
  <u> _those who can identify issues from their field experiences_ </u>   
空間現象を扱う上で重要なのは現象の大域性と局所性の違いを理解することです。局所的な課題をフィールドで見出し、その課題解決を汎用的な形（またはその逆）で示す意欲のある人を望みます。  
In dealing with spatial phenomena, it is important to understand the gap between the global and local nature of phenomena. 
We want members who are willing to find local issues in the field and explore solutions to those issues in a generic way (or vice versa).


- <u> _多様性に理解のある人_ </u>   
  <u> _those who understand diversity_ </u>   
性別や人種、年齢などの個性を認め合い、多様なメンバーとのコミュニティー形成に賛同する人を望みます。  
We want members who appreciate individuality in terms of gender, race, age, etc., and who agree to form a community with diverse members.  

- <u> _コミュニティへの貢献意欲のある人_ </u>    
  <u> _those who desire to contribute to community activities_ </u>    
研究は個々人が進めるべき仕事ではないと考えます。 
それぞれの成果や理解を他のメンバーと共有し、議論することで知見を蓄積し、互いに支え合うために研究室が存在します。 
これは学会や学外の研究会、OSS活動、国際組織などでも同様です。  
We believe that research is not a task that should be pursued by each individual. 
The laboratory exists to support each other by accumulating knowledge through sharing and discussing the results progresses. 
This attitude should be worth not only for laboratory, but also for academic societies, off-campus research groups, OSS activities, and international organizations.  


- <u> _ポジティブ思考ができる人_</u>   
  <u> _those who has potitive minds_</u>   
人間誰しも波がありますが、研究者と仕事しているときだけはできる限りポジティブ思考になりましょう。 
なお、研究に批判は必要不可欠ですが、「批判＝人格否定」ではありません。 
「批判＝思いやり」です。そして「無批判＝無関心」です。   
We should try to think as positively as you can when you are working with researchers. 
Although criticism is essential in research, it does not mean that criticism is a denial of your personality. 
"Criticism = compassion", and "non-criticism = indifference".   


<br>

# 研究者の方へ
# To researchers

学振やその他ファンドを利用してポスドクとして研究室に参加を希望の方はテーマが合致していれば積極的に受け入れたいと思います。 
一般の研究者の方で当研究室との共同研究に興味がある方もぜひInquiryページよりご連絡ください。  

If you are interested in joining our laboratory as a postdoctoral researcher using the JSPS or other funds, we would be happy to accept you as long as your research theme is compatible with us. 
We also welcome researchers who are interested in collaborating with us. 
Please contact us from the Inquiry page. 

<br>

# 技術者の方へ
# To engineers

テーマのすり合わせを行い、双方にメリットがあれば積極的に共同研究を実施したいと考えています。 
また、技術相談なども受け付けます。 
気軽にInquiryページよりご連絡ください。  

We are willing to conduct joint research with companies in case there are advantages for both parties.  
We are also open to technical consultations. 
Please feel free to contact us from the Inquiry page. 


