---
title: "Organization"
---

**The first goal of this R group is that people meet and learn from each other.**

In this page, we will detail how we will organize the R group and events. This organization has been approved during the first formal meeting but can change with time (any good idea is welcome!).

Some ideas are taken from the organization of the [Davis R Users' Group](https://d-rug.github.io/).

**Who can attend?** any R users, students, engineers, researchers, people from the Industry, non-french speakers are all welcome.

### Communicate

- Subscribe to the [r-in-grenoble newsletter](https://listes.univ-grenoble-alpes.fr/sympa/subscribe/r-in-grenoble?previous_action=info)

- Subscribe to the [calendar](https://r-in-grenoble.github.io/calendar.html) of the community

- Become a [member](https://docs.google.com/spreadsheets/d/1qdG7PPlRCAU8L6Hhq1D2zT0q9LWDUzBfq7mIzz_6Dm8/edit?usp=sharing) of the community

### Join working sessions

The main events we want to organize are monthly working sessions of 2 hours (16h-18h). 

- We will host presentations/tutorials on some R topics that can be useful to many people (e.g. optimization of code, the tidyverse, Rcpp, imputation, predictive models, image/text analysis, etc.) during 45-60 min.

- The second part of the session is about socializing and helping/getting helped. Everyone is free to do whatever they want. You could ask and answer some questions about specific problems you encounter when coding in R (come with your problems!). During this time, ~~beers,~~ cocktails and snacks will be offered by the [Grenoble Alpes Data Institute](https://data-institute.univ-grenoble-alpes.fr/) outside the room. So, it's also a good time to socialize with people.

- If you wish to share your R experience (on a specific topic) during a working session, please [contact us](mailto:matthieu.rolland@univ-grenoble-alpes.fr).

- If you wish to share your work with R in a lightning talk of 5 min (just after the main presentation), please contact us. 

### Attend scientific seminars

- Specific research topics that use R would take place in Lab seminars. We propose to announce these presentations with our newsletter and calendar so that people can go to the corresponding lab if they are interested.

- If we manage to invite some well-known speakers, we could host some special seminars.

### Blog and share your experience

- Every presentation could be completed with a blog post hosted on the [blog of the R group](blog/).

- We could also host some blog post without having to make a presentation. If you want to share a post, please [contact us](mailto:matthieu.rolland@univ-grenoble-alpes.fr). 

The blog will be relayed by [R-bloggers](https://www.r-bloggers.com/), which is read by thousands of people.

### Train

- During working sessions, you will probably be referred to some online content in order to learn more about R.

- According to R-users needs, we can organize and propose specific training sessions that can be integrated into MaiMoSiNE training calendar. 

- [Advanced R training course](https://www.adum.fr/phd/formation/catalogue.pl?mod=156596) for PhD students (in French).

### Get some help

- [Join the (french-speaking) slack of R users](https://join.slack.com/t/r-grrr/shared_invite/enQtMzI4MzgwNTc4OTAxLWZlOGZiZTBiMWU0NDQ3OTYzOGE1YThiODgwZWNhNWEyYjI4ZDJiNmNhY2YyYWI5YzFiOTFkNDYxYzkwODUwNWM).

- A [map and table with members](members.html) of the R group is available. One could contact people with some specific skills (referenced in the table). Don't hesitate to register by following the quick guidelines!

- [Some resources](https://privefl.github.io/advr38book/good-practices.html#getting-help).

