---
title: "Publications (2021~)"
---

# Thesis
## Bsc thesis
### FY2022
- 地理的加重ポアソン回帰による交通事故の空間分析
- Foliage height diversity (FHD)の地図化の試み
- 参加型AR地図アプリの開発の試み
- モンゴル国ウランバートルにおける高解像度衛星画像からの居住地判別モデルの検討
- 桜開花検出システムにおけるモデル選択とパラメータ調整に関する検討

### FY2021
- 位置情報付き街路写真を用いた桜開花検出システムの構築
- 地理データを用いた空間的主成分分析手法の比較
- Land Cover Classification System (LCCS) のための階層画像分類モデルの検討
- アフリカ地域における時系列衛星画像データを用いた植生変動傾向分析

# Journal papers 
## peer-review
- Shin, N., Saitoh, T. M., <u>Tsutsumida, N.</u> (2024) Retrieval of cherry flowering phenology on Flickr and YouTube: a case study along the Tarumi railway, Gifu, Japan. Frontiers in Sustainable Tourism, https://doi.org/3.10.3389/frsut.2024.1280685.
- Comber A. and <u>Tsutsumida N.</u> (2023) Geographically weighted accuracy for hard and soft land cover classifications: 5 approaches with coded illustrations, International Journal of Remote Sensing, 6233-625, https://doi.org/10.1080/01431161.2023.2264503.
- <u>Tsutsumida N.</u> and <u>Funada S.</u> (2023) Mapping cherry blossom phenology using a semi-automatic observation system with street level photos, Ecological Informatics, 102314. https://doi.org/10.1016/j.ecoinf.2023.102314
- Murakami D., <u>Tsutsumida N.</u>, Yoshida T., Nakaya T., Lu B., Harris P. (2023) A linearization for stable and fast geographically weighted Poisson regression, International Journal of Geographical Information Science, https://doi.org/10.1080/13658816.2023.2209811
- Osawa, T., <u>Tsutsumida, N.</u>, Iijima, H., Okabe K. (2023) Prediction of the visit and occupy of the sika deer (Cervus nippon) during the summer season using a virtual ecological approach, Sci Rep 13, 4007, https://doi.org/10.1038/s41598-023-31269-5. 
- Thongrueang, N., <u>Tsutsumida, N.</u>, Nakaya, T. (2023) The Impact of Changes in Anthropogenic Activity Caused by COVID-19 Lockdown on Reducing Nitrogen Dioxide Levels in Thailand Using Nighttime Light Intensity. Sustainability, 15, 4296. https://doi.org/10.3390/su15054296
- Shin N., Katsumata C., Miura T., <u>Tsutsumida N.</u>, Ichie T., Kotani A., Nakagawa M., Khoon K.L., Kobayashi H., Kumagai T., Tei S., Pungga R.A.S., Yamada T., Kameda A., Yanagisawa M., Nasahara K., Muraoka H., Ichii K., Tokumoto Y. (2023) Perspective: Improving the accuracy of plant phenology observations and land-cover and land-use detection by optical satellite remote-sensing in the Asian tropics, Front. For. Glob. Chang., vol. 6, Feb. 2023. https://doi.org/10.3389/ffgc.2023.1106723.
- Ohata S., Osawa T., Sato N., <u>Tsutsumida N.</u> (2022) Large, concealed islands in the urban sea: Scattered surrounding green space enhances the quality of grassland habitats in urban parks, Tokyo, Urban Ecosystems, https://doi.org/10.1007/s11252-022-01311-x
- Tran T.A., Saizen I., <u>Tsutsumida N.</u>, Venkatesh R., Le N.H., Nguyen V.A., Nguyen V.L., Thi T.N., Truong P.M. (2022) Flood vulnerability assessment at the local scale using remote sensing and GIS techniques: a case study in Da Nang City, Vietnam,Journal of Water and Climate Change, 13 (9): 3217–3238. https://doi.org/10.2166/wcc.2022.029
- Shin N., Kotani A., Tei S., <u> Tsutsumida N.</u> (2022) Monitoring of cherry flowering phenology with Google Trends. PLoS ONE 17(7): e0271648. https://doi.org/10.1371/journal.pone.0271648.
- Percival J.E.H., <u> Tsutsumida N.</u>, Murakami D., Yoshida T., and Nakaya T. (2022) gwpcorMapper: an interactive mapping tool for exploring geographically weighted correlation and partial correlation in high-dimensional geospatial datasets, Journal of Geovisualization and Spatial Analysis, 6, 17. https://doi.org/10.1007/s41651-022-00111-3
- <u>Tsutsumida N.</u>, Shin N., and Miura T. (2022) Evaluation of Land Surface Phenology for Autumn Leaf Color Change Based on Citizen Reports across Japan, Remote Sensing, 14(9), 2017. https://doi.org/10.3390/rs14092017
- Doi H., Osawa T., <u>Tsutsumida N.</u> (2022) Assessing the potential repercussions of the COVID-19 pandemic on global SDG attainment, Discover Sustainability 3, 2. https://doi.org/10.1007/s43621-021-00067-2.
- Nagai S., Maruya Y., Saito T.M., <u>Tsutsumida N.</u> (2021) Usefulness of Social Sensing Using Text Mining of Tweets for Detection of Autumn Phenology, Frontiers in Forests and Global Change, 4, 149, https://doi.org/10.3389/ffgc.2021.659910.
- <u>堤田成政</u>，吉田崇紘，村上大輔，中谷友樹（2021）地理的加重法の研究動向と今後の展望，GIS-理論と応用-, 29(1), 11-21. [[postprint](./share/202104GISA_GWreview_postprint.pdf)]
- Tran T.A., Venkatesh R., Nguyen V. L., Saizen I., <u>Tsutsumida N.</u> (2021) A GIS-based Approach for Flood Vulnerability Assessment in Hoa Vang District, Danang City, Vietnam, IOP Conference Series: Earth and Environmental Science, 652(1) 012003.
- Dida J., Tiburan C., <u>Tsutsumida N.</u>, Saizen I. (2021) Carbon Stock Estimation of Selected Watersheds in Laguna, Philippines Using InVEST, Philippine Journal of Science, 150 (2): 501-513
- Rustiadi E., Pravitasari A.E., Setiawan Y., Mulya S.P., Pribadi D.O., <u>Tsutsumida N.</u>  (2021) Impact of Continuous Jakarta Megacity Urban Expansion on the Formation of the Jakarta-Bandung Conurbation over the Rice Farm Regions, Cities, 111, 103000, https://doi.org/10.1016/j.cities.2020.103000

## non peer-review
- Doi H., Osawa T., <u>Tsutsumida N.</u> (2023) The role of large language models in ecology and biodiversity conservation: Opportunities and Challenges. Authorea. June 12, 2023. https://doi.org/10.22541/au.168657324.49460085/v1
- <u>Funada S.</u> and <u>Tsutsumida N.</u> (2022)  Mapping cherry blossoms from geotagged street-level photos, bioRxiv, https://doi.org/10.1101/2022.01.18.476550
- <u>堤田成政</u>（2021）再現可能性を重視したオンラインでのジオコンピュテーション教育， GIS-理論と応用．[[postprint](./share/202111GISedu_postprint.pdf)]

# Conference proceedings 
## peer-review
- Adhikari R., <u>Tsutsumida N.</u>, Bhardwaj A., An index-based flood mapping using stokes parameters of multi-temporal SAR images: 2019 Hagibis flood event of Ibaraki, Japan,IGARSS 2023 - 2023 IEEE International Geoscience and Remote Sensing Symposium proceedings, 2023, 7194-7197.
- <u>Tsutsumida N.</u>, Nasahara K., Tadono T., Birch T., Erickson T., 10-meter resolution land cover classification mapping using sentinel-2 and dynamic world,IGARSS 2023 - 2023 IEEE International Geoscience and Remote Sensing Symposium proceedings, 2023, 2954-2957.
- <u>Tsutsumida N.</u>, Kato A., Osawa T., Doi H., Mapping forest vertical structure attributes with gedi, sentinel-1, and Sentinel-2, IGARSS 2023 - 2023 IEEE International Geoscience and Remote Sensing Symposium proceedings, 2023, 538-541.
- <u>Tsutsumida N.</u>, Murakami D., Yoshida T., Nakaya T., Binbin L., Harris P., and Comber A. (2022) A Comparison of Geographically Weighted Principal Components Analysis Methodologies, 15th International Conference on Spatial Information Theory (COSIT 2022), https://doi.org/10.4230/LIPIcs.COSIT.2022.21
- Murakami D., <u>Tsutsumida N.</u>, Yoshida T., and Nakaya T. (2022) Large-Scale Spatial Prediction by Scalable Geographically Weighted Regression: Comparative Study, 15th International Conference on Spatial Information Theory (COSIT 2022), https://doi.org/10.4230/LIPIcs.COSIT.2022.12
- Comber A., Harris P., Murakami D., <u>Tsutsumida N.</u>, Brunsdon C. Geographically Varying Coefficient Regression: GWR-Exit and GAM-On?, 15th International Conference on Spatial Information Theory (COSIT 2022), https://doi.org/10.4230/LIPIcs.COSIT.2022.13
- <u>Tsutsumida N.</u>, Zhao J., Nasahara K., and Tadono T. Land cover classification from street-level photos, IGARSS2022, 17-22 July 2022, KL, Malaysia. 
- <u>Funada S.</u> and <u> Tsutsumida N.</u> (2022)  Mapping cherry blossoms from geotagged street-level photos, IGARSS2022, 17-22 July 2022, KL, Malaysia. 
- <u>Tsutsumida N.</u>, Murakami D., Yoshida T., Nakaya T., Lu B., Harris P. and Comber A. A comparison of Geographically Weighted Principal Components Analysis methodologies, COSIT 2022, accepted.
- Murakami D., <u>Tsutsumida N.</u>, Yoshida T., Nakaya T.,Large-scale spatial prediction by scalable geographically weighted regression: Comparative study, COSIT2022, accepted.
- Murakami D., <u>Tsutsumida N.</u>, Yoshida T., Nakaya T., Lu B. and Harris P. Stable geographically weighted Poisson regression for count data, submitted to GIScience 2021, https://doi.org/10.25436/E2X59B.
- Yoshida T., Murakami D., Seya H., <u>Tsutsumida N.</u>, and Nakaya T. Geographically weighted regression for compositional data: An application to the U.S. household income compositions, GIScience 2021, https://doi.org/10.25436/E2G599.
- Kato A. and <u>Tsutsumida N.</u> Deep learning with 3D laser data to identify tree species, SilviLaser 2021.

## non peer-review
- <u>黄晨安</u>、<u>堤田 成政</u>. 1kmメッシュ別滞在人口データを用いた時系列パターン分類手法の開発, , 第32回地理情報システム学会 学術研究発表大会, 2023. (**大会優秀発表賞**) https://confit.atlas.jp/guide/event-img/gisa2023/F2-01/public/pdf?type=in
- <u>堤田成政</u>, 村上大輔, 吉田崇紘, 中谷友樹. 総合指標作成のためのSpatially Hierarchical Benefit of the Doubt (SH-BoD)の提案, 第32回地理情報システム学会 学術研究発表大会, 2023. 
https://confit.atlas.jp/guide/event-img/gisa2023/F8-03/public/pdf?type=in
- 村上大輔 , <u>堤田 成政</u>, 吉田 崇紘, 中谷 友樹. Sub-model aggregationによる地理的加重回帰の安定化・高速化, 第32回地理情報システム学会 学術研究発表大会, 2023. 
https://confit.atlas.jp/guide/event-img/gisa2023/F8-04/public/pdf?type=in
- <u>堤田成政</u>, 村上大輔, 吉田崇紘, 中谷友樹, 多変量地理空間データからの総合指標作成手法の比較, 第31回地理情報システム学会 学術研究発表大会, 2022.
- 村上大輔 , <u>堤田 成政</u>, 吉田 崇紘, 中谷 友樹. 疎なカウントデータのための地理的加重ポアソン回帰の安定化・高速化, 第30回地理情報システム学会学術研究発表大会，2021．
- <u>堤田 成政</u>, 村上大輔 , 吉田 崇紘, 中谷 友樹. カーネルの重みをスパース推定する新たな地理加重回帰の提案, 第30回地理情報システム学会学術研究発表大会，2021．
- Thongrueang N., Nakaya T., <u>Tsutsumida N.</u> The Impact of COVID-19 Outbreak on Air Quality in Thailand, 地理情報システム学会第30回学術研究発表大会，2021．
- 吉田 崇紘, 村上大輔 , 瀬谷創,  <u>堤田 成政</u>, 中谷 友樹. 定数和制約と誤差相関を考慮した組成データのための地理的加重回帰, 第30回地理情報システム学会学術研究発表大会，2021．

# Others including presentations (without proceedings)
## invited
- <u>堤田 成政</u>. 大学・大学院でのジオデータサイエンス教育の実践，第32回地理情報システム学会 学術研究発表大会 教育委員会企画ミニシンポジウム「教育におけるデータサイエンスと地理情報：実践と課題」, 2023.
- <u> Tsutsumida N </u>. Social Sensing: An important research resource, National Geographic session in Science Agora, 2022.
- <u>堤田 成政</u>. 地理的加重法による空間内挿， ESTRELA No. 341, 2022.
- <u>堤田 成政</u>. 土地被覆分類データの空間精度・空間誤差, 写真測量学会関西支部第109回テクニカルセミナー／空間情報話題交換会.
- <u>堤田成政</u>．地理的加重モデルの開発と空間データ解析，ROIS-DS 成果報告会，2021年2月．  

## others
- <u> Tsutsumida N. </u>, Nasahara K., Tadono T. Enhancing Land Cover Classification Mapping with Dynamic World and Decision Fusion, AGU Annual Meeting 2023, 11 Dec, 2023. (Highlighted poster)
- Miura T., Yamamoto Y., Nagai S., <u> Tsutsumda N. </u>, Ichii K. Snow detection in Himawari-8 Advanced Himawari Imager NDVI for improved autumn phenology monitoring, AGU Annual Meeting 2023, 12 Dec, 2023. (poster)
- <u>渋谷南帆</u>, <u> 堤田成政</u>. パノプティックシーングラフによる土地被覆オブジェクト間の関係性抽出，第32回地理情報システム学会 学術研究発表大会 学生フリーテーマ発表会 成果発表セッション, 2023.
- <u>黄晨安</u>, <u> 堤田成政</u>.  1 kmメッシュ別滞在人口データを用いたコロナ禍における都市人口の時空間分析, JpGU2023, 2023. (poster)
- Miura T., Shin N., Yamamoto Y., <u>Tsutsumida N.</u>, Ichii K. Detecting Snow Contamination in Advanced
Himawari Imager NDVI Time Series Data for
Improved Autumn Phenology Characterization, JpGU2023, 2023. 
- <u> 堤田成政</u> , Joseph Percival, 吉田崇紘, 村上大輔, 中谷友樹. 探索的空間データ解析のためのインタラクティブ空間相関マッピング,CSIS DAYS2022（オンライン）, 2022.　 優秀共同研究発表賞！ 
- <u> Tsutsumida N. </u> and <u>Mochizuki R. </u> (2022) Uncertain Vegetation Trends by Index Selections, 2022 Geo for Good Summit at Google, 2022. (poster)
- <u>舟田宗弥</u>，<u>堤田成政</u>. ⾞載カメラ画像を⽤いた桜開花マッピング，第69回日本生態学会大会, 3月15日（オンライン），（ポスター）, 2022.
- <u>Tsutsumida N.</u>, Zhao J., Nasahara K. and Tadono T. Estimating Land Cover from Geo-tagged Street-level Photos, AGU Fall meeting 2021, 2021 (poster).
- Miura T., Nagai S., <u>Tsutsumida N.</u>, Yamamoto Y. Himawari-8 AHI NDVI Temporal Signature Variability of Broadleaf Deciduous Forests Along Temperature, Elevation, and Latitudinal Gradients in Northern Japan. JpGU 2021, 2021.
- <u>堤田成政</u>．1982 年以降の土地被覆変動解析，第23回 環境リモートセンシングシンポジウム，千葉大学，2021年2月18日．
- Yoshida T., Murakami D., Seya H., <u>Tsutsumida N.</u>, Nakaya T. Geographically weighted regression for compositional data, Data Science Workshop, Center for Data Science and Service Research, Tohoku University, 2021.

<br>
  


