---
title: "R community in Grenoble"
subtitle: "First meeting"
author: "Florian Privé & Magali Richard"
date: "May 24, 2017"
output:
  xaringan::moon_reader:
    self_contained: false
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, width = 65)
knitr::opts_chunk$set(echo = FALSE, fig.align='center', dev='png', dpi = 95)
```

class: inverse, center, middle

# Introduction
## Questionnaire results

---

## Research Topics 

- Quantification d'incertitudes/Analyse de sensibilité
- Biodiversity, bioinformatics
- Epigenetic and Cancer
- Ecology of communities
- Turbulence
- Graph signal processing
- Sociologie du journalisme et des marchés. Mediatisation de la finance
- Mixture model, Change-point
- Biodiversity modelling, global change, statistical ecology
- Numerical probability
- Statistics
- Mixture models
- Formal Methods
- Géomatique - Système d'information géographique
- Hidden Markov Models

---

## Scientific seminar

- A dedicated seminar

- Occasionnal

- => A ‘R-users’ tag for seminars

  - Label an internal seminar with the ‘R-user’ tag and invite the community

  - Invite a speaker and organize a special ‘R-user’ seminar

---

## Practical courses

- R and Python and R/Python

- All levels (beginners, intermediate, developpers)

- Monthly to occasionnal

- => Associated with wine and beers social event

---

## Social events

- In laboratories

- Monthly to occasionnal

- => Associated with pratical courses / seminars

---

## Community R and Python

- A mailing list (open)

- A website

  - News

  - Calendar

  - People

---

class: inverse, center, middle

# Project Idea

---

## Starting point of the project

- Learned a lot from [R-bloggers](https://www.r-bloggers.com/). Now, I [blog](https://privefl.github.io/blog/) to share my knowledge in return.

- Development of [lots of communities around R](https://jumpingrivers.github.io/meetingsR/). Already 9 in France, but none in Grenoble.

- Many people want/need to improve their skills in R.

<br>

#### The first goal is that people meet and learn from each other

---

## An example of useR group

[Davis R Users' Group](https://d-rug.github.io/):

- many talks and tutorials

- website and blog

- weekly meetings have 5-15 attendees but much more online traffic on posts that result from talks

  - working sessions
  
  - talks/tutorials

---

## Possible organization

- Work session with a possible talk at the beginning on a topic that is useful to many people (e.g. optimization of code, plots for publication, manipulation of data frames, Rcpp, imputation, predictive models, image/text analysis, etc.). Could be organized as a social event.

- Pub for precise R talks during lab seminars: (e.g. *Anomaly detection in streaming time series data with R*).

--- 

### Blog (on R-bloggers)

- Release all R talks/tutorials/seminars as blog posts

- Host blog posts (without need of presentation)

---

## Website

https://r-python-grenoble.github.io/

- calendar

- members on a map and in a table

--- 

## Members


We don't know everyone and we are sorry if we have forgotten some people.

Don't forget to let people know about this group. Especially students, post-docs and engineers who make a lot of R code.


---

## To be determined

- language: english?

- meeting location: IMAG?

- frequency: monthly?

- which (public) info on the members?

- relay infos: website, mailing list and one person by lab?

---

class: inverse, center, middle

# Link with other institutions

---

class: center

## The Grenoble Alpes Data Institute 

is willing to pay for food/drinks.

--- 

## The Python community

We do **NOT** want to organize the Python community

We are open to have a **website** and a **newsletter** in common for both communities.

--- 

## MaiMoSiNE - Education

To be determined 

[Presentation](R-MaiMoSiNE.pdf)